services:
    mongodb:
        image: mongo:latest
        container_name: mongodb-container
        restart: always
        ports:
            - '27017:27017'
        volumes:
            - ./mongodb-data:/data/db
    node-app:
        build: .
        container_name: besttrip-node-app-container
        ports:
            - '8123:8123'
        volumes:
            - ./:/usr/src/app
            - /usr/src/app/node_modules
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro
        depends_on:
            - mongodb
volumes:
    mongodb-data:
