services:
  mongo_db:
    image: mongo:latest
    container_name: mongo_db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
  node_app:
    build: .
    container_name: besttrip-node-app
    ports:
      - "8123:8123"
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongo_db
